### ISSUE TITLE
Zahlenausgabe ist nicht lokalisiert

### ISSUE THREAD

**Issue by hholzer** [justimmo/wordpress-plugin#10]
Preis und Flächenangaben werden mit bei der Dezimalstelle mit "." getrennt (Spracheinstellung Deutsch).

**Comment by cbusoi** [comment]
Das kann ich erklären wie man das behebt.




2017-06-13 14:31 GMT+02:00 Harald Holzer <notifications@github.com>:

**Comment by resqonline** [comment]
geht die Erklärung auch öffentlich? Ich möchte da nämlich auch gerne das richtige Format haben ;-)

**Comment by hholzer** [comment]
wurde mit den release 1.0.4 behoben.

patch:
https://github.com/justimmo/wordpress-plugin/commit/5eb76f7a55ae212c29a57e78e3d8f963fcabe269
