### ISSUE TITLE
On first install plugin triggers an error

### ISSUE THREAD

**Issue by cbusoi** [justimmo/wordpress-plugin#4]
On first install, the plugin triggers an error. There is no conflict with former versions.
Tested in Wordpress 4.5.3

Not sure how to bypass this to test....

![image](https://cloud.githubusercontent.com/assets/1805182/17328784/e5f41ef2-58bf-11e6-8a35-c2d3ecd270d1.png)

**Comment by mihalacherazvan** [comment]
I think the problem is caused because i used a short syntax notation for arrays, which is unsupported in php versions older than 5.4 ? Can you confirm if this is the problem by checking your server's php version, please ? In the meantime, i will start to replace the short syntax with standard one.

**Comment by cbusoi** [comment]
This version is running on the test server...

PHP 5.3.2-1ubuntu4.30 with Suhosin-Patch (cli) (built: Apr 17 2015 15:02:03)
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies with DBG v4.6.3, (C) 2000,2012, by Dmitri Dmitrienko

I understand... so then we should switch to old syntax. On the wild, we will have a lot of shared hosts with old php versions. If it's a show stopper for the development we should define a min php version. If not, switching the syntax is the best idea... up to you ;)

**Comment by mihalacherazvan** [comment]
Thank you for the info. I think the best solution would be to switch to older syntax. I will proceed with changing this.

**Comment by mihalacherazvan** [comment]
I have replaced all occurrences of array shorthand notation with the standard one. Please try installing it again.

**Comment by cbusoi** [comment]
Hi Razvan,

i fixed also the syntax of some arrays 57b8ffb949297070c62209c646d0d3ceba90c9eb ... so shoot a git pull ... but i have now this issue here ... problem is how to enter api credentials if the plugin doesn't fire up ...

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Username not set' in /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plugin/includes/justimmo-sdk/Justimmo/Api/JustimmoApi.php:397 Stack trace: #0 /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plugin/includes/justimmo-sdk/Justimmo/Api/JustimmoApi.php(452): Justimmo\Api\JustimmoApi->throwError('Username not se...') #1 /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plugin/includes/justimmo-sdk/Justimmo/Api/JustimmoApi.php(100): Justimmo\Api\JustimmoApi->setUsername(false) #2 /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plugin/public/class-jiwp-public.php(223): Justimmo\Api\JustimmoApi->__construct(false, false, Object(Psr\Log\NullLogger), Object(Justimmo\Cache\NullCache)) #3 /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plu in /kunden/justimmo-projekte/wordpress.justimmo.at/public_html/web/wp-content/plugins/wordpress-plugin/includes/justimmo-sdk/Justimmo/Api/JustimmoApi.php on line 397

**Comment by mihalacherazvan** [comment]
I have added an admin notification in case the api credentials fields are not completed. I've also handled front-end errors that appear in this case. Please verify if it works now.
